### ISSUE TITLE
yarn uninstall nodejs on debian

### ISSUE THREAD

**Issue by Clayment** [manala/ansible-role-yarn#1]
I got a problem with this role, it seems to have been recently added to the default configuration. 

When I setup my vagrant machine it install the package nodejs, then yarn which remove nodejs, and then crash later on when it tries to install npm dependencies. 

Do you have any idea how to prevent yarn from removing nodejs/npm ?
Or at least how can i target a specific revision for the role which add yarn ?

**Comment by nervo** [comment]
Oo Strange behavior...
Could you show the provision logs ?

**Comment by Clayment** [comment]
That's the log from my provision.
[manala-yarn-fail.txt](https://github.com/manala/ansible-role-yarn/files/773952/manala-yarn-fail.txt)

Additionnally when I try to install nodejs inside the vm : 
```
sudo apt-get install nodejs       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  yarn
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 0 B/7323 kB of archives.
After this operation, 9143 kB of additional disk space will be used.
```

**Comment by nervo** [comment]
I think, i got it.

Yarn conflicts with old npm version:
```

**Comment by Clayment** [comment]
I switched to '6' inside my ansible/group_vars/app.yml file and it seems to work. Thanks again. 

```yaml
---

app_options:

  php_version:    '7.0'
  nodejs_version: '6'
  mysql:          true
  mysql_version:  '5.6'
  phantomjs:      false
  supervisor:     false
```
